In [105]:
import pandas as pd
import os
os.getcwd()
os.chdir(r'C:\GYANENDRA\INFORMATION_TECHNILOGY_PROJECTS\PROJECT_AI')

In [106]:
df=pd.read_csv("titanic.csv")

In [107]:
#check mising value 
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [108]:
Age_Mean = df['Age'].mean()

In [109]:
df['Age'].fillna(Age_Mean, inplace=True)

C:\Users\rkshw\AppData\Local\Temp\ipykernel_25724\1491142997.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(Age_Mean, inplace=True)

In [110]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [111]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

C:\Users\rkshw\AppData\Local\Temp\ipykernel_25724\3744086084.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [112]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [113]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [114]:
#Get
x = df.drop(['PassengerId','Name','Cabin','Fare','Ticket', 'Survived'], axis=1)

In [115]:
#get the dependent variable 
y = df['Survived']

In [116]:
#convert non numeric independent variable to numeric 
x= pd.get_dummies(x,dtype=int)

In [117]:
#Divide the data into training and test 
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=.20)

In [118]:
#fit the model 
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [119]:
xtest['Predicted_value'] = model.predict(xtest)

In [120]:
xtest.head(10)

,Pclass,Age,SibSp,Parch,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Predicted_value
832,3,29.699118,0,0,0,1,1,0,0,0
195,1,58.000000,0,0,1,0,1,0,0,1
555,1,62.000000,0,0,0,1,0,0,1,0
563,3,29.699118,0,0,0,1,0,0,1,0
421,3,21.000000,0,0,0,1,0,1,0,0
858,3,24.000000,0,3,1,0,1,0,0,1
433,3,17.000000,0,0,0,1,0,0,1,0
14,3,14.000000,0,0,1,0,0,0,1,1
414,3,44.000000,0,0,0,1,0,0,1,0
69,3,26.000000,2,0,0,1,0,0,1,0